name: DevboxIOS
options:
  bundleIdPrefix: com.example
settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  DevboxIOS:
    type: application
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.devbox
    sources:
      - path: Sources/App
    info:
      path: Sources/App/Info.plist
