version: "0.5"

processes:
  android-emulator:
    command: "bash -lc '. \"/Users/abueide/code/devbox-plugins/examples/react-native/.devbox/virtenv/android/scripts/env.sh\"; android_run_emulator_service'"
    availability:
      restart: "on_failure"
    shutdown:
      signal: 15
      timeout: 120
